#!/usr/bin/env python3
"""Dashboard freshness detector: did the freshest generated signal reach data/?

2026-07-22 root-cause context
-----------------------------
The daily dashboard publish runs as the LAST step of ``daily_main_follow.ps1``,
AFTER the child ``daily_pipeline.ps1`` (``-SkipVercel``) has finished. The ntfy
notification lives INSIDE that child (step 5); the dashboard publish lives in the
wrapper's step 4. If the wrapper dies mid-run (host sleep / task timeout), the
orphaned child keeps running to completion and STILL fires ntfy with fresh data,
while the wrapper's publish is silently lost -> the dashboard freezes on
yesterday's build even though ntfy shows today's numbers. That is the
"更新時刻は新しいのに中身が古い" failure, seen on 2026-07-22 (ntfy=07-22,
dashboard=07-21).

What this checks
----------------
It compares the newest ``today_signals_YYYYMMDD.json`` date in:

  * ``results_csv/``  -- generated by the pipeline; the source of truth for
    "what was computed today".
  * ``apps/dashboards/alpaca-next/data/`` -- committed = what Vercel serves.

If ``results_csv`` is AHEAD of ``data/``, a publish was missed -> STALE. Its one
job is the publish gap between "generated" and "served"; it does NOT judge whether
the pipeline itself ran (both dirs equally behind today is a different failure,
covered by ``check_rolling_freshness.py`` / ``self_monitor``).

Pair it with ``publish_data_to_vercel.ps1 -AutoLatest`` (the self-heal): run this
detector FIRST to alert on the recurrence, then the self-heal to fix it.

Exit codes
----------
  0  fresh   -- data/ has the newest generated date (or nothing to compare).
  2  stale   -- results_csv is ahead of data/ (publish gap).
  1  error   -- bad usage / IO error.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys

_SIGNAL_RE = re.compile(r"today_signals_(\d{8})\.json$")

# repo layout: <root>/scripts/check_dashboard_freshness.py
_REPO_ROOT_DEFAULT = Path(__file__).resolve().parents[1]


def newest_signal_date(directory: Path) -> int | None:
    """Return the max embedded YYYYMMDD (as int) among today_signals files.

    Numeric parse (not lexical) so a lingering future-dated stub cannot outrank
    real data; 8-digit zero-padded means int order == chronological order.
    Returns None when the directory is missing or has no matching file.
    """
    if not directory.is_dir():
        return None
    best: int | None = None
    for entry in directory.iterdir():
        m = _SIGNAL_RE.search(entry.name)
        if not m:
            continue
        n = int(m.group(1))
        if best is None or n > best:
            best = n
    return best


def _generated_at(directory: Path, date_int: int | None) -> str | None:
    """Best-effort read of ``generated_at`` for the given date (for reporting)."""
    if date_int is None:
        return None
    path = directory / f"today_signals_{date_int}.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    val = payload.get("generated_at")
    return val if isinstance(val, str) else None


def _fmt(date_int: int | None) -> str:
    if date_int is None:
        return "(none)"
    s = str(date_int)
    return f"{s[0:4]}-{s[4:6]}-{s[6:8]}"


def check_freshness(results_dir: Path, data_dir: Path) -> dict:
    """Compare generated (results_csv) vs served (data/) newest signal dates.

    status:
      "fresh"   -- data_date >= results_date, or results has nothing to publish.
      "stale"   -- results_date > data_date (a dashboard publish was missed).
      "unknown" -- neither dir has any today_signals file.
    """
    results_date = newest_signal_date(results_dir)
    data_date = newest_signal_date(data_dir)

    if results_date is None and data_date is None:
        status = "unknown"
    elif results_date is None:
        # Nothing generated to publish; whatever is served is not "stale".
        status = "fresh"
    elif data_date is None or results_date > data_date:
        status = "stale"
    else:
        status = "fresh"

    return {
        "status": status,
        "results_date": results_date,
        "data_date": data_date,
        "results_date_str": _fmt(results_date),
        "data_date_str": _fmt(data_date),
        "results_generated_at": _generated_at(results_dir, results_date),
        "data_generated_at": _generated_at(data_dir, data_date),
    }


def _notify_stale(result: dict) -> None:
    """Fire a single ntfy WARN when a publish gap is detected."""
    title = (
        f"Dashboard STALE: served {result['data_date_str']} < "
        f"generated {result['results_date_str']}"
    )
    body = (
        "ダッシュボードの publish が取りこぼされています "
        "(ntfy は新しいのに中身が古い型)。\n"
        f"generated (results_csv): {result['results_date_str']} "
        f"@ {result.get('results_generated_at') or '?'}\n"
        f"served   (data/)      : {result['data_date_str']} "
        f"@ {result.get('data_generated_at') or '?'}\n"
        "self-heal: publish_data_to_vercel.ps1 -AutoLatest"
    )
    try:
        from common.publishers.ntfy import NtfyPublisher

        pub = NtfyPublisher()
        if not pub.is_configured():
            print("[ntfy] NTFY_TOPIC 未設定のため送信スキップ")
            return
        res = pub.send_text(title, body, tags="rotating_light,warning", priority=5)
        print(f"[ntfy] 送信 ok={getattr(res, 'ok', '?')}")
    except Exception as exc:  # noqa: BLE001
        print(f"[ntfy] 送信失敗: {exc}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--repo-root",
        default=os.getenv("QTS_REPO_ROOT", str(_REPO_ROOT_DEFAULT)),
        help="repo root (contains results_csv/ and apps/dashboards/...).",
    )
    parser.add_argument(
        "--results-dir",
        default=None,
        help="override results_csv dir (default <repo-root>/results_csv).",
    )
    parser.add_argument(
        "--data-dir",
        default=None,
        help="override dashboard data dir "
        "(default <repo-root>/apps/dashboards/alpaca-next/data).",
    )
    parser.add_argument(
        "--notify",
        action="store_true",
        help="send an ntfy WARN when a stale publish gap is detected.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the result as a JSON line (for machine consumers).",
    )
    args = parser.parse_args(argv)

    root = Path(args.repo_root)
    results_dir = Path(args.results_dir) if args.results_dir else root / "results_csv"
    data_dir = (
        Path(args.data_dir)
        if args.data_dir
        else root / "apps" / "dashboards" / "alpaca-next" / "data"
    )

    result = check_freshness(results_dir, data_dir)

    if args.json:
        print(json.dumps(result, ensure_ascii=False))
    else:
        print(
            f"[dashboard_freshness] status={result['status']} "
            f"generated={result['results_date_str']} "
            f"served={result['data_date_str']}"
        )

    if result["status"] == "stale":
        print(
            "[dashboard_freshness] STALE: dashboard publish was missed "
            f"(generated {result['results_date_str']} > "
            f"served {result['data_date_str']}). "
            "Run publish_data_to_vercel.ps1 -AutoLatest to self-heal."
        )
        if args.notify:
            _notify_stale(result)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
