#!/usr/bin/env python3
"""Dashboard freshness detector: did the freshest generated signal reach data/?

2026-07-22 root-cause context
-----------------------------
The daily dashboard publish runs as the LAST step of ``daily_main_follow.ps1``,
AFTER the child ``daily_pipeline.ps1`` (``-SkipVercel``) has finished. The ntfy
notification lives INSIDE that child (step 5); the dashboard publish lives in the
wrapper's step 4. If the wrapper dies mid-run (host sleep / task timeout), the
orphaned child keeps running to completion and STILL fires ntfy with fresh data,
while the wrapper's publish is silently lost -> the dashboard freezes on
yesterday's build even though ntfy shows today's numbers. That is the
"更新時刻は新しいのに中身が古い" failure, seen on 2026-07-22 (ntfy=07-22,
dashboard=07-21).

What this checks
----------------
It compares the newest ``today_signals_YYYYMMDD.json`` date in:

  * ``results_csv/``  -- generated by the pipeline; the source of truth for
    "what was computed today".
  * ``apps/dashboards/alpaca-next/data/`` -- committed = what Vercel serves.

If ``results_csv`` is AHEAD of ``data/``, a publish was missed -> STALE. Its one
job is the publish gap between "generated" and "served"; it does NOT judge whether
the pipeline itself ran (both dirs equally behind today is a different failure,
covered by ``check_rolling_freshness.py`` / ``self_monitor``).

Pair it with ``publish_data_to_vercel.ps1 -AutoLatest`` (the self-heal): run this
detector FIRST to alert on the recurrence, then the self-heal to fix it.

Exit codes
----------
  0  fresh   -- data/ has the newest generated date (or nothing to compare).
  2  stale   -- results_csv is ahead of data/ (publish gap).
  1  error   -- bad usage / IO error.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import subprocess
import sys

_SIGNAL_RE = re.compile(r"today_signals_(\d{8})\.json$")
_BUNDLE_RE = re.compile(r"dashboard_bundle_(\d{8})\.json$")

# 本番 URL。dashboard は静的 export で data/*.json を **build 時に取り込む** ため、
# JSON は URL で配信されない。到達確認は描画済み HTML に run_id が現れるかで行う。
_PROD_URL_DEFAULT = "https://quant-trading-monitor.vercel.app/"

# git push から Vercel の build/deploy 完了までの許容遅延。2026-08-17 に実測で
# 約 20 分かかった実績があるため、これより短いと正常な遅延を誤検知する。
_DEPLOY_GRACE_MINUTES_DEFAULT = 30

# repo layout: <root>/scripts/check_dashboard_freshness.py
_REPO_ROOT_DEFAULT = Path(__file__).resolve().parents[1]

# ``python scripts/check_dashboard_freshness.py`` puts *scripts/* on sys.path[0],
# NOT the repo root, and cwd is not on sys.path for file-invoked scripts. Without
# this insert ``from common.publishers.ntfy import ...`` raises
# ``ModuleNotFoundError: No module named 'common'`` whenever the launcher runs us
# from any cwd -- which silently killed 4 consecutive stale alerts (2026-07-23..26).
# Anchor on __file__ so the import is cwd-independent by construction.
if str(_REPO_ROOT_DEFAULT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT_DEFAULT))

# Failed sends are queued here and retried on the next invocation so a transient
# (or systemic) ntfy outage degrades into a late alert, never a silent one.
_PENDING_NAME = "ntfy_pending_dashboard_freshness.json"


def newest_signal_date(directory: Path) -> int | None:
    """Return the max embedded YYYYMMDD (as int) among today_signals files.

    Numeric parse (not lexical) so a lingering future-dated stub cannot outrank
    real data; 8-digit zero-padded means int order == chronological order.
    Returns None when the directory is missing or has no matching file.
    """
    if not directory.is_dir():
        return None
    best: int | None = None
    for entry in directory.iterdir():
        m = _SIGNAL_RE.search(entry.name)
        if not m:
            continue
        n = int(m.group(1))
        if best is None or n > best:
            best = n
    return best


def _generated_at(directory: Path, date_int: int | None) -> str | None:
    """Best-effort read of ``generated_at`` for the given date (for reporting)."""
    if date_int is None:
        return None
    path = directory / f"today_signals_{date_int}.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    val = payload.get("generated_at")
    return val if isinstance(val, str) else None


def _fmt(date_int: int | None) -> str:
    if date_int is None:
        return "(none)"
    s = str(date_int)
    return f"{s[0:4]}-{s[4:6]}-{s[6:8]}"


# --- served basis: origin ref ------------------------------------------------
# publish_data_to_vercel.ps1 は `git commit-tree` で **origin tip** に commit を作り
# `<sha>:refs/heads/<branch>` へ直接 push する。local の working tree と branch ref は
# 意図的に一切触らない (2026-07-30 の root-cause fix)。よって local の data/ は永久に
# 古く、それを "served" とみなすと **毎日** STALE になる (2026-08-19 の誤警報:
# served=2026-08-11 と出続けたが origin は当日分を配信済みだった)。
# publish 自身の verify が使っているのと同じ `origin/<branch>` を基準にする。
_PUBLISH_REF_DEFAULT = "origin/claude/monitor-webapp"
_DATA_REL_DEFAULT = "apps/dashboards/alpaca-next/data"


def _git(repo_root: Path, *args: str, timeout: float = 30.0) -> str | None:
    """read-only な git を実行して stdout を返す。失敗は None (= 不明)。"""
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo_root), *args],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
        )
    except Exception:  # noqa: BLE001 - git 不在 / timeout は "不明" 扱い
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout


def _fetch_ref(repo_root: Path, ref: str, timeout: float = 30.0) -> bool:
    """`origin/<branch>` を最新化する。失敗しても致命ではない (既存 ref で続行)。"""
    remote, _, branch = ref.partition("/")
    if not remote or not branch:
        return False
    return (
        _git(repo_root, "fetch", "--quiet", remote, branch, timeout=timeout) is not None
    )


def newest_signal_date_ref(
    repo_root: Path, ref: str, data_rel: str = _DATA_REL_DEFAULT
) -> int | None:
    """`ref` の data/ に **コミット済** の最新 today_signals 日付 (int) を返す。"""
    out = _git(repo_root, "ls-tree", "--name-only", ref, f"{data_rel}/")
    if out is None:
        return None
    best: int | None = None
    for line in out.splitlines():
        m = _SIGNAL_RE.search(line.strip())
        if not m:
            continue
        n = int(m.group(1))
        if best is None or n > best:
            best = n
    return best


def _generated_at_ref(
    repo_root: Path,
    ref: str,
    date_int: int | None,
    data_rel: str = _DATA_REL_DEFAULT,
) -> str | None:
    """`ref` にコミット済の today_signals から generated_at を読む (報告用)。"""
    if date_int is None:
        return None
    out = _git(repo_root, "show", f"{ref}:{data_rel}/today_signals_{date_int}.json")
    if out is None:
        return None
    try:
        payload = json.loads(out)
    except ValueError:
        return None
    val = payload.get("generated_at") if isinstance(payload, dict) else None
    return val if isinstance(val, str) else None


def check_freshness(
    results_dir: Path,
    data_dir: Path,
    *,
    repo_root: Path | None = None,
    served_ref: str | None = None,
    fetch: bool = True,
) -> dict:
    """Compare generated (results_csv) vs served newest signal dates.

    served の基準:
      ``served_ref`` を渡すとその git ref (既定の呼び出しでは
      ``origin/claude/monitor-webapp``) に **コミット済** の data/ を served とみなす。
      これが publish 側の verify と同じ基準で、唯一 Vercel が build する実体でもある。
      ref が読めない (git 不在 / offline / ref 不明) 場合だけ従来どおり
      ローカル ``data_dir`` にフォールバックする。``served_basis`` に採用元を返す。

    status:
      "fresh"   -- data_date >= results_date, or results has nothing to publish.
      "stale"   -- results_date > data_date (a dashboard publish was missed).
      "unknown" -- neither source has any today_signals file.
    """
    results_date = newest_signal_date(results_dir)

    served_basis = "local"
    data_date: int | None = None
    if served_ref and repo_root is not None:
        if fetch:
            _fetch_ref(repo_root, served_ref)
        data_date = newest_signal_date_ref(repo_root, served_ref)
        if data_date is not None:
            served_basis = f"ref:{served_ref}"
    if served_basis == "local":
        data_date = newest_signal_date(data_dir)

    if results_date is None and data_date is None:
        status = "unknown"
    elif results_date is None:
        # Nothing generated to publish; whatever is served is not "stale".
        status = "fresh"
    elif data_date is None or results_date > data_date:
        status = "stale"
    else:
        status = "fresh"

    return {
        "status": status,
        "results_date": results_date,
        "data_date": data_date,
        "results_date_str": _fmt(results_date),
        "data_date_str": _fmt(data_date),
        "results_generated_at": _generated_at(results_dir, results_date),
        "data_generated_at": (
            _generated_at_ref(repo_root, served_ref, data_date)
            if served_basis.startswith("ref:") and repo_root is not None and served_ref
            else _generated_at(data_dir, data_date)
        ),
        "served_basis": served_basis,
    }


def newest_bundle(data_dir: Path) -> dict | None:
    """data/ で最も新しい dashboard_bundle_*.json を読む (無ければ None)。"""
    best: tuple[int, Path] | None = None
    try:
        entries = list(data_dir.iterdir())
    except OSError:
        return None
    for path in entries:
        m = _BUNDLE_RE.search(path.name)
        if not m:
            continue
        key = int(m.group(1))
        if best is None or key > best[0]:
            best = (key, path)
    if best is None:
        return None
    try:
        payload = json.loads(best[1].read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 - 壊れた manifest は「不明」扱い
        return None
    if not isinstance(payload, dict):
        return None
    payload["_path"] = str(best[1])
    return payload


def newest_bundle_ref(
    repo_root: Path, ref: str, data_rel: str = _DATA_REL_DEFAULT
) -> dict | None:
    """`ref` にコミット済の最新 dashboard_bundle manifest を読む。

    watchdog も従来はローカル data/ の manifest を見ていたため、publish が
    commit-tree で origin にしか書かない現行仕様では manifest を見つけられず
    ``unknown`` に落ちていた (= 本番不達を検出できない)。
    """
    out = _git(repo_root, "ls-tree", "--name-only", ref, f"{data_rel}/")
    if out is None:
        return None
    best: tuple[int, str] | None = None
    for line in out.splitlines():
        name = line.strip()
        m = _BUNDLE_RE.search(name)
        if not m:
            continue
        key = int(m.group(1))
        if best is None or key > best[0]:
            best = (key, name)
    if best is None:
        return None
    blob = _git(repo_root, "show", f"{ref}:{best[1]}")
    if blob is None:
        return None
    try:
        payload = json.loads(blob)
    except ValueError:
        return None
    if not isinstance(payload, dict):
        return None
    payload["_path"] = f"{ref}:{best[1]}"
    iso = _git(repo_root, "log", "-1", "--format=%cI", ref, "--", best[1])
    payload["_committed_iso"] = (iso or "").strip() or None
    return payload


def _minutes_since_iso(iso: str | None) -> float | None:
    """commit 時刻からの経過分。ref 基準の manifest には mtime が無いため。"""
    if not iso:
        return None
    try:
        ct = datetime.fromisoformat(iso)
    except ValueError:
        return None
    return (datetime.now(tz=ct.tzinfo) - ct).total_seconds() / 60.0


def _fetch_served_html(url: str, timeout: float) -> str | None:
    """本番 HTML を取得する。取得できなければ None (未確認と区別する)。"""
    try:
        import urllib.request

        req = urllib.request.Request(url, headers={"Cache-Control": "no-cache"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            return resp.read().decode("utf-8", errors="replace")
    except Exception:  # noqa: BLE001 - ネットワーク失敗は "unknown"
        return None


def _minutes_since(path_str: str | None) -> float | None:
    if not path_str:
        return None
    try:
        mtime = Path(path_str).stat().st_mtime
    except OSError:
        return None
    return (datetime.now(timezone.utc).timestamp() - mtime) / 60.0


def check_served_run(
    data_dir: Path,
    *,
    url: str = _PROD_URL_DEFAULT,
    grace_minutes: float = _DEPLOY_GRACE_MINUTES_DEFAULT,
    timeout: float = 20.0,
    repo_root: Path | None = None,
    served_ref: str | None = None,
) -> dict:
    """publish した run_id が **本番で実際に配信されているか** を確認する。

    既存の freshness チェックは results_csv と data/ という **どちらもローカルの
    ファイル** を比べるだけなので、git push が成功していれば「fresh」と答える。
    Vercel の build が落ちた / 発火しなかった場合を検出できない
    (2026-08-17: publish は成功し blob も一致していたのに本番は朝の run のままだった)。

    status:
      "served"        -- 本番 HTML に manifest の run_id が現れた
      "deploy_lagging"-- まだ現れないが grace 内 (正常な遅延の可能性)
      "deploy_missing"-- grace を超えても現れない (build 不達の疑い)
      "unknown"       -- manifest 不在 / run_id 不明 / HTML 取得失敗
    """
    manifest = None
    if served_ref and repo_root is not None:
        manifest = newest_bundle_ref(repo_root, served_ref)
    if manifest is None:
        manifest = newest_bundle(data_dir)
    if not manifest:
        return {"status": "unknown", "reason": "no_bundle_manifest"}
    run_id = str(manifest.get("source_run_id") or "")
    if not run_id:
        return {"status": "unknown", "reason": "manifest_has_no_run_id"}

    age = (
        _minutes_since_iso(manifest.get("_committed_iso"))
        if manifest.get("_committed_iso")
        else _minutes_since(manifest.get("_path"))
    )
    html = _fetch_served_html(url, timeout)
    if html is None:
        return {
            "status": "unknown",
            "reason": "fetch_failed",
            "run_id": run_id,
            "url": url,
        }

    if run_id in html:
        return {"status": "served", "run_id": run_id, "url": url, "age_min": age}

    lagging = age is not None and age < grace_minutes
    return {
        "status": "deploy_lagging" if lagging else "deploy_missing",
        "run_id": run_id,
        "url": url,
        "age_min": age,
        "grace_minutes": grace_minutes,
    }


def _pending_path(root: Path) -> Path:
    return root / "logs" / _PENDING_NAME


def _load_pending(root: Path) -> list[dict]:
    try:
        raw = json.loads(_pending_path(root).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    return [x for x in raw if isinstance(x, dict)] if isinstance(raw, list) else []


def _save_pending(root: Path, items: list[dict]) -> None:
    path = _pending_path(root)
    try:
        if not items:
            path.unlink(missing_ok=True)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(items, ensure_ascii=False, indent=2), encoding="utf-8"
        )
    except OSError as exc:
        print(f"[ntfy] pending キューの永続化に失敗 (次回持ち越し不可): {exc}")


def _send_one(item: dict) -> tuple[bool, str]:
    """Attempt one ntfy send. Returns (ok, detail). Never raises."""
    try:
        from common.publishers.ntfy import NtfyPublisher

        pub = NtfyPublisher()
        if not pub.is_configured():
            return False, "NTFY_TOPIC 未設定"
        res = pub.send_text(
            item["title"], item["body"], tags="rotating_light,warning", priority=5
        )
        ok = bool(getattr(res, "ok", False))
        return ok, f"ok={ok}"
    except Exception as exc:  # noqa: BLE001
        return False, f"{type(exc).__name__}: {exc}"


def _notify_stale(result: dict, root: Path, now: str) -> None:
    """Fire an ntfy WARN for this gap, flushing any carried-over failures first.

    A send failure is NOT swallowed: the alert is queued to ``logs/`` and retried
    on every later invocation (including "fresh" ones) until it lands, so a broken
    notifier degrades into a late alert instead of a silent one.
    """
    title = (
        f"Dashboard STALE: served {result['data_date_str']} < "
        f"generated {result['results_date_str']}"
    )
    body = (
        "ダッシュボードの publish が取りこぼされています "
        "(ntfy は新しいのに中身が古い型)。\n"
        f"generated (results_csv): {result['results_date_str']} "
        f"@ {result.get('results_generated_at') or '?'}\n"
        f"served   (data/)      : {result['data_date_str']} "
        f"@ {result.get('data_generated_at') or '?'}\n"
        "self-heal: publish_data_to_vercel.ps1 -AutoLatest"
    )
    _flush_pending(root, now, extra={"title": title, "body": body, "queued_at": now})


def _flush_pending(root: Path, now: str, extra: dict | None = None) -> None:
    """Retry every queued alert (plus ``extra``); keep whatever still fails."""
    queue = _load_pending(root)
    if extra is not None:
        # Collapse duplicates: the same gap re-detected daily is one alert.
        if not any(x.get("title") == extra["title"] for x in queue):
            queue.append(extra)
    if not queue:
        return

    carried = [x for x in queue if x.get("queued_at") != now]
    if carried:
        print(f"[ntfy] 前回までの未送信 {len(carried)} 件を再送します (持ち越し)")

    still: list[dict] = []
    for item in queue:
        ok, detail = _send_one(item)
        age = item.get("queued_at", "?")
        if ok:
            print(f"[ntfy] 送信 ok=True (queued_at={age})")
            continue
        item["attempts"] = int(item.get("attempts", 0)) + 1
        item["last_error"] = detail
        item["last_attempt_at"] = now
        still.append(item)
        print(
            f"[ntfy] 送信失敗 ({detail}) -> 次回に持ち越し "
            f"[queued_at={age} attempts={item['attempts']}]"
        )
    _save_pending(root, still)
    if still:
        print(
            f"[ntfy][PENDING] 未送信 {len(still)} 件が "
            f"{_pending_path(root)} に残っています"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--repo-root",
        default=os.getenv("QTS_REPO_ROOT", str(_REPO_ROOT_DEFAULT)),
        help="repo root (contains results_csv/ and apps/dashboards/...).",
    )
    parser.add_argument(
        "--results-dir",
        default=None,
        help="override results_csv dir (default <repo-root>/results_csv).",
    )
    parser.add_argument(
        "--data-dir",
        default=None,
        help="override dashboard data dir "
        "(default <repo-root>/apps/dashboards/alpaca-next/data).",
    )
    parser.add_argument(
        "--notify",
        action="store_true",
        help="send an ntfy WARN when a stale publish gap is detected.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the result as a JSON line (for machine consumers).",
    )
    parser.add_argument(
        "--check-served",
        action="store_true",
        help=(
            "本番 URL を取得し、publish した run_id が実際に配信されているか確認する "
            "(git push 成功だけでは Vercel の build 不達を検出できないため)。"
        ),
    )
    parser.add_argument(
        "--prod-url",
        default=os.getenv("QTS_DASHBOARD_URL", _PROD_URL_DEFAULT),
        help="本番 dashboard の URL (--check-served 用)。",
    )
    parser.add_argument(
        "--deploy-grace-minutes",
        type=float,
        default=float(
            os.getenv("QTS_DEPLOY_GRACE_MINUTES", _DEPLOY_GRACE_MINUTES_DEFAULT)
        ),
        help=(
            "publish から deploy 完了までの許容遅延 (分)。既定 30。"
            "2026-08-17 に約 20 分の実績があるため短くしすぎない。"
        ),
    )
    parser.add_argument(
        "--served-ref",
        default=os.getenv("QTS_PUBLISH_REF", _PUBLISH_REF_DEFAULT),
        help=(
            "served の基準にする git ref (既定 origin/claude/monitor-webapp)。"
            "publish は commit-tree で origin tip にしか書かないため、ローカルの "
            "data/ を基準にすると毎日 STALE になる。"
        ),
    )
    parser.add_argument(
        "--served-basis",
        choices=("ref", "local"),
        default=None,
        help=(
            "served をどこから読むか。既定は ref (= origin)。"
            "ただし --data-dir を明示した呼び出しは『その dir を測れ』という意味なので "
            "local に固定する (明示引数 > 既定)。"
        ),
    )
    parser.add_argument(
        "--no-fetch",
        action="store_true",
        help="--served-basis ref のとき git fetch を省く (offline / 高速確認用)。",
    )
    args = parser.parse_args(argv)

    root = Path(args.repo_root)
    results_dir = Path(args.results_dir) if args.results_dir else root / "results_csv"
    data_dir = (
        Path(args.data_dir)
        if args.data_dir
        else root / "apps" / "dashboards" / "alpaca-next" / "data"
    )

    # 明示引数が既定より強い: --data-dir を渡された呼び出しは、その dir 自体を
    # 測ることが目的なので origin ref で上書きしない。
    basis = args.served_basis or os.getenv("QTS_SERVED_BASIS") or (
        "local" if args.data_dir else "ref"
    )
    served_ref = args.served_ref if basis == "ref" else None
    result = check_freshness(
        results_dir,
        data_dir,
        repo_root=root,
        served_ref=served_ref,
        fetch=not args.no_fetch,
    )

    if args.json:
        print(json.dumps(result, ensure_ascii=False))
    else:
        print(
            f"[dashboard_freshness] status={result['status']} "
            f"generated={result['results_date_str']} "
            f"served={result['data_date_str']} "
            f"basis={result.get('served_basis', 'local')}"
        )

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    # --- deploy watchdog: publish した run が本番に届いているか -----------------
    # 既存の stale 判定はローカル同士の比較なので、Vercel の build 不達を検出できない。
    served: dict | None = None
    if args.check_served:
        served = check_served_run(
            data_dir,
            url=args.prod_url,
            grace_minutes=args.deploy_grace_minutes,
            repo_root=root,
            served_ref=served_ref,
        )
        print(
            f"[dashboard_deploy] status={served['status']} "
            f"run={served.get('run_id') or '-'} "
            f"age_min={served.get('age_min') if served.get('age_min') is None else round(served['age_min'], 1)}"
        )
        if served["status"] == "deploy_missing":
            print(
                "[dashboard_deploy] MISSING: publish 済みの run が本番に出ていません "
                f"(run={served.get('run_id')}, {args.deploy_grace_minutes} 分超過)。"
                " Vercel の build 発火を確認してください。"
            )
            if args.notify:
                _notify_stale(
                    {
                        "status": "deploy_missing",
                        "results_date_str": str(served.get("run_id") or "?"),
                        "data_date_str": "not served",
                        **result,
                    },
                    root,
                    now,
                )
            return 3

    if result["status"] == "stale":
        print(
            "[dashboard_freshness] STALE: dashboard publish was missed "
            f"(generated {result['results_date_str']} > "
            f"served {result['data_date_str']}). "
            "Run publish_data_to_vercel.ps1 -AutoLatest to self-heal."
        )
        if args.notify:
            _notify_stale(result, root, now)
        return 2

    # Fresh now, but an earlier alert may never have landed. Retry it here so a
    # missed warning still reaches the phone once ntfy recovers.
    if args.notify:
        _flush_pending(root, now)
    return 0


if __name__ == "__main__":
    sys.exit(main())
