"""Materialize and validate one coherent dashboard bundle before publication.

The dashboard files are generated by separate steps.  This command joins the
same-date ``today_signals``, ``pipeline`` and execution ``recon`` artifacts,
repairs only deterministic measurements, validates their lineage, and writes a
small manifest.  It never invents zero for unavailable data and performs no
network or broker operations.
"""

from __future__ import annotations

import argparse
from datetime import datetime
import hashlib
import json
import logging
import math
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_execution_recon import (  # noqa: E402
    funnel_counts_from_signals,
    patch_pipeline_exit,
    patch_pipeline_funnel,
)

logger = logging.getLogger(__name__)

SYSTEMS = tuple(f"sys{i}" for i in range(1, 8))
FUNNEL_PHASES = ("Tgt", "FILpass", "STUpass", "TRDlist", "Entry")
ALL_PHASES = (*FUNNEL_PHASES, "Exit")
FUNNEL_SOURCE = "today_signals.funnel"
SPY_TARGET_REASON = "shared_universe_not_applicable_to_spy_only"


class BundleContractError(ValueError):
    """Raised when a bundle cannot be published without misrepresenting data."""


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise BundleContractError(f"required file missing: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001 - converted to a contract error
        raise BundleContractError(f"invalid JSON: {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise BundleContractError(f"JSON root must be an object: {path}")
    return payload


def _atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    tmp.replace(path)


def _sha256(path: Path) -> str:
    """Hash the artifact's content with line endings normalized to LF.

    The producer runs on Windows, so these JSON files sit in the working tree
    with CRLF, while git stores and checks out LF.  Hashing the raw bytes here
    records a digest the dashboard can never reproduce after checkout, which
    fail-closes the whole page on a perfectly valid publish.  Normalizing makes
    the digest identical on both sides while still detecting any real content
    difference (stale or partial publishes).  The reader applies the same
    normalization.
    """
    raw = path.read_bytes()
    return hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()


def _valid_count(value: Any) -> bool:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return False
    if isinstance(value, float) and (
        not math.isfinite(value) or not value.is_integer()
    ):
        return False
    return int(value) >= 0


def _parse_timestamp(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def _phase_map(system: dict[str, Any]) -> dict[str, dict[str, Any]]:
    phases = system.get("phases")
    if not isinstance(phases, list):
        return {}
    return {
        str(phase.get("name")): phase
        for phase in phases
        if isinstance(phase, dict) and phase.get("name")
    }


def _invalid_unmeasured_reason(phase: dict[str, Any]) -> str | None:
    if phase.get("measured") is False and phase.get("count") is not None:
        return "count_present_but_measurement_unverified"
    reason = phase.get("unmeasured_reason")
    return str(reason) if reason else None


def validate_dashboard_bundle(
    pipeline: dict[str, Any],
    signals: dict[str, Any],
    *,
    expected_date: str,
    require_exit: bool,
) -> tuple[list[str], list[str], dict[str, int]]:
    """Validate schema, measurement honesty and cross-file run lineage."""
    errors: list[str] = []
    warnings: list[str] = []
    summary = {"funnel_measured": 0, "funnel_total": 35, "exit_measured": 0}

    if pipeline.get("schema") != "signal_pipeline/v1":
        errors.append(f"pipeline.schema={pipeline.get('schema')!r}")
    if pipeline.get("date") != expected_date:
        errors.append(
            f"pipeline.date={pipeline.get('date')!r}, expected={expected_date}"
        )
    if signals.get("date") != expected_date:
        errors.append(f"signals.date={signals.get('date')!r}, expected={expected_date}")

    run_id = str((signals.get("meta") or {}).get("run_id") or "")
    if not run_id:
        errors.append("signals.meta.run_id is missing")
    if pipeline.get("source_signals_run_id") != run_id:
        errors.append(
            "pipeline.source_signals_run_id does not match signals.meta.run_id"
        )

    signal_systems = signals.get("systems")
    pipeline_systems = pipeline.get("systems")
    if not isinstance(signal_systems, dict):
        errors.append("signals.systems must be an object")
        signal_systems = {}
    if not isinstance(pipeline_systems, dict):
        errors.append("pipeline.systems must be an object")
        pipeline_systems = {}

    expected_systems = set(SYSTEMS)
    for source_name, systems in (
        ("signals", signal_systems),
        ("pipeline", pipeline_systems),
    ):
        actual_systems = set(systems)
        if actual_systems != expected_systems:
            errors.append(
                f"{source_name}.systems mismatch "
                f"missing={sorted(expected_systems - actual_systems)} "
                f"extra={sorted(actual_systems - expected_systems)}"
            )

    counts_by_system = funnel_counts_from_signals(signals)
    for system_id in SYSTEMS:
        if system_id not in signal_systems:
            errors.append(f"signals.{system_id} missing")
        system = pipeline_systems.get(system_id)
        if not isinstance(system, dict):
            errors.append(f"pipeline.{system_id} missing")
            continue
        phase_by_name = _phase_map(system)
        raw_phases = system.get("phases")
        phase_names = (
            [
                str(phase.get("name"))
                for phase in raw_phases
                if isinstance(phase, dict) and phase.get("name")
            ]
            if isinstance(raw_phases, list)
            else []
        )
        if len(phase_names) != len(set(phase_names)):
            errors.append(f"{system_id} contains duplicate phase names")
        if set(phase_by_name) != set(ALL_PHASES) or len(phase_names) != len(ALL_PHASES):
            missing = sorted(set(ALL_PHASES) - set(phase_by_name))
            extra = sorted(set(phase_by_name) - set(ALL_PHASES))
            errors.append(
                f"{system_id} phase set mismatch missing={missing} extra={extra}"
            )

        previous: int | None = None
        for phase_name in FUNNEL_PHASES:
            phase = phase_by_name.get(phase_name)
            if phase is None:
                continue
            measured = phase.get("measured") is True
            count = phase.get("count")
            valid = _valid_count(count)
            spy_target = counts_by_system.get(system_id, {}).get("Tgt")
            shared_spy_target = (
                system_id == "sys7"
                and phase_name == "Tgt"
                and spy_target is not None
                and spy_target != 1
            )

            if shared_spy_target:
                if measured or count is not None:
                    errors.append(
                        f"{system_id}.Tgt must be unavailable, not fabricated"
                    )
                if phase.get("unmeasured_reason") != SPY_TARGET_REASON:
                    errors.append(
                        f"{system_id}.Tgt missing explicit unavailable reason"
                    )
                previous = None
                continue

            if not measured or not valid:
                errors.append(
                    f"{system_id}.{phase_name} is not an honest measured integer "
                    f"(count={count!r}, measured={phase.get('measured')!r})"
                )
                continue
            summary["funnel_measured"] += 1

            if (
                phase.get("source") == FUNNEL_SOURCE
                and phase.get("source_run_id") != run_id
            ):
                errors.append(f"{system_id}.{phase_name} source_run_id mismatch")
            parsed = int(count)
            if previous is not None and parsed > previous:
                errors.append(
                    f"{system_id} funnel is non-monotonic at {phase_name}: "
                    f"{parsed} > {previous}"
                )
            previous = parsed

        entry = phase_by_name.get("Entry") or {}
        if entry.get("measured") is True and system.get("final_signals") != entry.get(
            "count"
        ):
            errors.append(f"{system_id}.final_signals does not match measured Entry")

        exit_phase = phase_by_name.get("Exit") or {}
        if exit_phase.get("measured") is True and _valid_count(exit_phase.get("count")):
            summary["exit_measured"] += 1
        elif require_exit:
            errors.append(f"{system_id}.Exit is unmeasured")

    sys7_target = counts_by_system.get("sys7", {}).get("Tgt")
    expected_measured = 34 if sys7_target is not None and sys7_target != 1 else 35
    if summary["funnel_measured"] != expected_measured:
        errors.append(
            f"expected {expected_measured} measured funnel phases, "
            f"got {summary['funnel_measured']}"
        )
    if require_exit and summary["exit_measured"] != 7:
        errors.append(
            f"expected 7 measured Exit phases, got {summary['exit_measured']}"
        )
    elif not require_exit and summary["exit_measured"] != 7:
        warnings.append(
            f"Exit coverage is partial: {summary['exit_measured']}/7 (not required)"
        )

    return errors, warnings, summary


def materialize_dashboard_bundle(
    *,
    results_dir: Path,
    date_str: str,
    require_exit: bool = False,
) -> dict[str, Any]:
    """Materialize a deterministic same-date bundle and return its manifest."""
    compact = date_str.replace("-", "")
    signals_path = results_dir / f"today_signals_{compact}.json"
    pipeline_path = results_dir / f"pipeline_{compact}.json"
    recon_path = results_dir / f"recon_{compact}.json"
    manifest_path = results_dir / f"dashboard_bundle_{compact}.json"

    signals = _load_json(signals_path)
    pipeline = _load_json(pipeline_path)
    if signals.get("date") != date_str or pipeline.get("date") != date_str:
        raise BundleContractError(
            "same-date contract failed before repair: "
            f"signals={signals.get('date')!r}, pipeline={pipeline.get('date')!r}, "
            f"expected={date_str!r}"
        )

    _, _, funnel_status = patch_pipeline_funnel(pipeline, signals)
    if funnel_status != "ok":
        raise BundleContractError(f"funnel materialization failed: {funnel_status}")

    recon: dict[str, Any] | None = None
    lineage_warnings: list[str] = []
    exit_status = "no_recon"
    if recon_path.exists():
        recon = _load_json(recon_path)
        recon_run_id = recon.get("source_signals_run_id")
        signals_run_id = (signals.get("meta") or {}).get("run_id")
        if recon.get("date") != date_str:
            raise BundleContractError(
                f"recon.date={recon.get('date')!r}, expected={date_str!r}"
            )
        if require_exit:
            # recon が「どの execution input も current run 由来と確認できた」と
            # 明示していない限り、Exit を current run の実測として公開しない。
            # (同日 rerun で Step5b/5c が skip / 失敗し、前 run の
            #  paper_orders / exit_orders が残っているケース)
            lineage = recon.get("execution_lineage")
            if isinstance(lineage, dict):
                unverified = sorted(
                    name
                    for name, state in lineage.items()
                    if state not in {"verified", "missing"}
                )
                if unverified:
                    detail = ", ".join(f"{n}={lineage[n]}" for n in unverified)
                    raise BundleContractError(
                        "execution inputs are not bound to the current signals run: "
                        f"{detail}"
                    )
            elif recon.get("execution_lineage_ok") is False:
                raise BundleContractError("recon reports execution_lineage_ok=false")
            if recon_run_id and recon_run_id != signals_run_id:
                raise BundleContractError(
                    "recon.source_signals_run_id does not match signals.meta.run_id "
                    f"({recon_run_id!r} != {signals_run_id!r})"
                )
            if not recon_run_id:
                # Transition path for older daily-main producers.  Same-date is
                # insufficient: require the recon to have been generated after
                # the exact signals artifact.  New producers always emit the
                # run_id above, so this warning naturally disappears.
                recon_at = _parse_timestamp(recon.get("generated_at"))
                signals_at = _parse_timestamp(signals.get("generated_at"))
                if recon_at is None or signals_at is None or recon_at < signals_at:
                    raise BundleContractError(
                        "legacy recon has no source_signals_run_id and is older "
                        "than the current signals run"
                    )
                lineage_warnings.append(
                    "legacy recon lineage verified by generated_at only; "
                    "upgrade producer to source_signals_run_id"
                )
        _, _, exit_status = patch_pipeline_exit(pipeline, recon)
    if require_exit and exit_status != "ok":
        raise BundleContractError(f"Exit materialization failed: {exit_status}")

    signals_sha = _sha256(signals_path)
    pipeline["source_signals_sha256"] = signals_sha
    if recon is not None:
        pipeline["source_recon_sha256"] = _sha256(recon_path)
        pipeline["source_recon_generated_at"] = recon.get("generated_at")

    # Deterministic timestamp: rerunning the same source bundle must be a no-op.
    materialized_at = (recon or {}).get("generated_at") or signals.get("generated_at")
    if not isinstance(materialized_at, str) or not materialized_at:
        raise BundleContractError(
            "source generated_at is missing; cannot materialize deterministically"
        )
    pipeline["materialized_at"] = materialized_at

    # Preserve honesty for any non-funnel/legacy value that remains unverified.
    # The UI can now distinguish this producer-contract violation from a true
    # unavailable/null measurement.
    for system in (pipeline.get("systems") or {}).values():
        if not isinstance(system, dict):
            continue
        for phase in system.get("phases") or []:
            if not isinstance(phase, dict):
                continue
            reason = _invalid_unmeasured_reason(phase)
            if reason and not phase.get("unmeasured_reason"):
                phase["unmeasured_reason"] = reason

    errors, warnings, measurement = validate_dashboard_bundle(
        pipeline,
        signals,
        expected_date=date_str,
        require_exit=require_exit,
    )
    warnings.extend(lineage_warnings)
    if errors:
        raise BundleContractError("; ".join(errors))

    _atomic_write_json(pipeline_path, pipeline)
    files: dict[str, dict[str, str]] = {
        "today_signals": {"name": signals_path.name, "sha256": signals_sha},
        "pipeline": {"name": pipeline_path.name, "sha256": _sha256(pipeline_path)},
    }
    sources: dict[str, dict[str, str]] = {}
    if recon is not None:
        # Recon may contain order-level detail and is not a public dashboard
        # artifact.  Record its hash as provenance without staging the file.
        sources["recon"] = {
            "name": recon_path.name,
            "sha256": _sha256(recon_path),
        }
    for key, stem in (
        ("narrative", "narrative"),
        ("alpaca_snapshot", "alpaca_snapshot"),
        # execution summary の ntfy 配信状態 (夜の実績通知)。無い日もあるので optional。
        ("notify_delivery", "notify_delivery"),
    ):
        optional_path = results_dir / f"{stem}_{compact}.json"
        if optional_path.exists():
            try:
                optional = _load_json(optional_path)
                if optional.get("date") != date_str:
                    raise BundleContractError("date mismatch")
                if key == "narrative" and not (
                    optional.get("headline") or optional.get("summary")
                ):
                    raise BundleContractError("headline/summary missing")
                if key == "notify_delivery":
                    # run を跨いだ混入を防ぐ: 別 run の配信状態を今日の bundle に
                    # 載せない。state の語彙も signals 側と揃っていることを要求する。
                    stamped = optional.get("source_signals_run_id")
                    current = str((signals.get("meta") or {}).get("run_id") or "")
                    if stamped and current and str(stamped) != current:
                        raise BundleContractError("run_id mismatch")
                    if optional.get("state") not in {
                        "accepted",
                        "failed",
                        "not_configured",
                        "not_attempted",
                    }:
                        raise BundleContractError(
                            f"unknown delivery state {optional.get('state')!r}"
                        )
                if key == "alpaca_snapshot":
                    equity = (optional.get("account") or {}).get("equity")
                    if (
                        optional.get("schema") != "alpaca_snapshot/v1"
                        or isinstance(equity, bool)
                        or not isinstance(equity, (int, float))
                        or not math.isfinite(float(equity))
                    ):
                        raise BundleContractError("schema/account.equity invalid")
            except BundleContractError as exc:
                warnings.append(f"optional {key} excluded: {exc}")
                continue
            files[key] = {
                "name": optional_path.name,
                "sha256": _sha256(optional_path),
            }

    manifest: dict[str, Any] = {
        "schema": "dashboard_bundle/v1",
        "date": date_str,
        "source_run_id": str((signals.get("meta") or {}).get("run_id") or ""),
        "materialized_at": materialized_at,
        "files": files,
        "sources": sources,
        "measurement": measurement,
        "warnings": warnings,
        # Persist source outcomes, not transient "changed N" counters.  The
        # latter differ between first materialization and an idempotent rerun
        # and would create a needless second data commit for identical input.
        "materialization": {
            "funnel_status": funnel_status,
            "exit_status": exit_status,
        },
    }
    _atomic_write_json(manifest_path, manifest)
    return manifest


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--date", required=True, help="対象日 (YYYY-MM-DD)")
    parser.add_argument(
        "--results-dir", default="results_csv", help="artifact directory"
    )
    parser.add_argument(
        "--require-exit",
        action="store_true",
        help="7 systems の execution recon/Exit measurement を必須にする",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        manifest = materialize_dashboard_bundle(
            results_dir=Path(args.results_dir),
            date_str=args.date,
            require_exit=args.require_exit,
        )
    except BundleContractError as exc:
        logger.error("dashboard bundle rejected: %s", exc)
        return 2
    measurement = manifest["measurement"]
    logger.info(
        "dashboard bundle ready: date=%s run=%s funnel=%s/%s Exit=%s/7",
        manifest["date"],
        manifest["source_run_id"],
        measurement["funnel_measured"],
        measurement["funnel_total"],
        measurement["exit_measured"],
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
